using System.Text; using System.Text.Json;
using Microsoft.Xna.Framework; using Microsoft.Xna.Framework.Graphics; using Microsoft.Xna.Framework.Input;

namespace RailPlanner;

public sealed class MainGame : Game
{
    readonly GraphicsDeviceManager graphics; SpriteBatch batch = null!; SpriteFont font = null!; Texture2D pixel = null!;
    RailProject project = new(); AnalysisResult analysis = new(); string mode = "SELECT", status = "READY";
    Guid? selectedStation, selectedTrain, selectedLine, selectedSection, pendingFrom; Vector2 camera = new(80,70); float zoom=.7f; MouseState oldMouse; KeyboardState oldKeys; int nextStation=1,nextTrain=1;
    bool renamingStation; readonly StringBuilder stationNameBuffer = new();
    public MainGame(){graphics=new GraphicsDeviceManager(this){PreferredBackBufferWidth=1440,PreferredBackBufferHeight=900};Content.RootDirectory="Content";IsMouseVisible=true;Window.Title="RailPlanner";Window.TextInput += OnTextInput;}
    protected override void LoadContent(){batch=new SpriteBatch(GraphicsDevice);font=Content.Load<SpriteFont>("DefaultFont");pixel=new Texture2D(GraphicsDevice,1,1);pixel.SetData(new[]{Color.White});}
    void OnTextInput(object? sender, TextInputEventArgs e){if(!renamingStation)return;if(e.Character=='\b'){if(stationNameBuffer.Length>0)stationNameBuffer.Length--;return;}if(e.Character=='\r'||e.Character=='\n')return;if(!char.IsControl(e.Character)&&stationNameBuffer.Length<40)stationNameBuffer.Append(e.Character);}
    protected override void Update(GameTime time)
    {
        var k=Keyboard.GetState();var m=Mouse.GetState();bool P(Keys x)=>k.IsKeyDown(x)&&!oldKeys.IsKeyDown(x);
        if(P(Keys.Enter)&&renamingStation){FinishStationRename();oldKeys=k;oldMouse=m;base.Update(time);return;}
        if(P(Keys.Escape)&&renamingStation){CancelStationRename();oldKeys=k;oldMouse=m;base.Update(time);return;}
        if(P(Keys.F1))mode="SELECT";if(P(Keys.F2)){mode="STATION";status="CLICK MAP TO ADD STATION";}if(P(Keys.F3)){mode="SECTION";pendingFrom=null;status="CLICK TWO STATIONS";}if(P(Keys.F4)){mode="TRAIN";status="CLICK A STATION TO CREATE A RUN";}if(P(Keys.F8)){mode="LINE VIEW";status="SELECT A LINE OR SEGMENT";}
        if(P(Keys.F9))StartStationRename();if(P(Keys.F10))ChangeStationTracks(1);if(P(Keys.F11))ChangeStationTracks(-1);
        if(P(Keys.F5))Save();if(P(Keys.F6))LoadProject();if(P(Keys.F7)){analysis=TimetableAnalyzer.Analyze(project);status=$"ANALYSIS: {analysis.Conflicts.Count} CONFLICTS / {analysis.Warnings.Count} WARNINGS";}
        if(P(Keys.D)&&selectedTrain.HasValue)Duplicate();if(P(Keys.Delete))Delete();if(P(Keys.Escape)){mode="SELECT";pendingFrom=null;selectedSection=null;}if(P(Keys.OemPlus)||P(Keys.Add))zoom=MathHelper.Clamp(zoom*1.1f,.25f,3f);if(P(Keys.OemMinus)||P(Keys.Subtract))zoom=MathHelper.Clamp(zoom/1.1f,.25f,3f);
        camera+=new Vector2((k.IsKeyDown(Keys.Left)?5:0)-(k.IsKeyDown(Keys.Right)?5:0),(k.IsKeyDown(Keys.Up)?5:0)-(k.IsKeyDown(Keys.Down)?5:0));
        if(m.LeftButton==ButtonState.Pressed&&oldMouse.LeftButton==ButtonState.Released){if(m.X<280&&m.Y>=54)ClickSidebar(new Vector2(m.X,m.Y));else if(m.X>=280&&m.Y>=54)Click(new Vector2(m.X,m.Y));}
        oldKeys=k;oldMouse=m;base.Update(time);
    }
    void StartStationRename(){if(selectedStation is not Guid id){status="SELECT A STATION FIRST";return;}var s=project.Stations.FirstOrDefault(x=>x.Id==id);if(s==null)return;stationNameBuffer.Clear();stationNameBuffer.Append(s.Name);renamingStation=true;mode="STATION EDIT";status="TYPE NAME - ENTER SAVE - ESC CANCEL";}
    void FinishStationRename(){if(selectedStation is not Guid id){CancelStationRename();return;}var s=project.Stations.FirstOrDefault(x=>x.Id==id);if(s!=null){var name=stationNameBuffer.ToString().Trim();if(name.Length>0){s.Name=name;status=$"RENAMED {s.Code}";}else status="NAME CANNOT BE EMPTY";}renamingStation=false;mode="SELECT";}
    void CancelStationRename(){renamingStation=false;mode="SELECT";status="RENAME CANCELLED";}
    void ChangeStationTracks(int delta){if(selectedStation is not Guid id){status="SELECT A STATION FIRST";return;}var s=project.Stations.FirstOrDefault(x=>x.Id==id);if(s==null)return;var value=Math.Clamp(s.Tracks+delta,1,20);if(value==s.Tracks){status=value==20?"MAXIMUM TRACKS: 20":"MINIMUM TRACKS: 1";return;}s.Tracks=value;status=$"{s.Code}: {s.Tracks} TRACKS";}
    void ClickSidebar(Vector2 p)
    {
        var y=104;
        foreach(var line in project.Lines){
            if(p.Y>=y&&p.Y<y+24){selectedLine=line.Id;selectedSection=null;mode="LINE VIEW";status=$"LINE {line.Number} SELECTED";return;}
            y+=26;
            if(selectedLine==line.Id){var route=LineRoute(line);if(route.Count>0)y+=30;foreach(var sec in line.Sections){if(p.Y>=y&&p.Y<y+34){selectedLine=line.Id;selectedSection=sec.Id;mode="LINE VIEW";status=$"SELECTED {line.Number}|{sec.Number}";return;}y+=36;}}
            y+=8;
        }
    }
    void Click(Vector2 screen)
    {
        var p=ScreenToMap(screen);var s=project.Stations.FirstOrDefault(x=>Vector2.Distance(new(x.X,x.Y),p)<18/zoom);
        if(mode=="STATION"&&s==null){s=new Station{Name=$"Station {nextStation}",Code=$"N{nextStation:00}",X=(int)p.X,Y=(int)p.Y};nextStation++;project.Stations.Add(s);selectedStation=s.Id;mode="SELECT";status=$"ADDED {s.Code}";return;}
        if(s==null){selectedStation=null;selectedTrain=null;return;}selectedStation=s.Id;
        if(mode=="SECTION"){if(pendingFrom==null){pendingFrom=s.Id;status=$"FROM {s.Code}: SELECT DESTINATION";}else if(pendingFrom!=s.Id){AddSection(pendingFrom.Value,s.Id);pendingFrom=null;mode="SELECT";}}else if(mode=="TRAIN"){AddTrain(s.Id);mode="SELECT";}
    }
    void AddSection(Guid a,Guid b){var line=project.Lines.FirstOrDefault()??new RailwayLine{Number="LK001",Name="Wroclaw - Klodzko"};if(!project.Lines.Contains(line))project.Lines.Add(line);if(line.Sections.Any(x=>(x.FromStationId==a&&x.ToStationId==b)||(x.FromStationId==b&&x.ToStationId==a))){status="SECTION EXISTS";return;}var A=project.Stations.First(x=>x.Id==a);var B=project.Stations.First(x=>x.Id==b);var sec=new RailSection{Number=line.Sections.Count+1,FromStationId=a,ToStationId=b,Geometry=new(){new(A.X,A.Y),new(B.X,B.Y)}};sec.Tracks.Add(new RailTrack{Name="1",Direction=TrackDirection.Forward});sec.Tracks.Add(new RailTrack{Name="2",Direction=TrackDirection.Reverse});line.Sections.Add(sec);status=$"ADDED {line.Number}|{sec.Number} {A.Code} -> {B.Code}";selectedLine=line.Id;selectedSection=sec.Id;}
    void AddTrain(Guid station){var other=project.Stations.FirstOrDefault(x=>x.Id!=station);if(other==null){status="ADD TWO STATIONS FIRST";return;}var t=new TrainRun{Number=$"IC {nextTrain++:000}",Name="New run"};t.Timetable.Add(new TimetableEntry{StationId=station,Kind=StopKind.Origin,Departure="08:00"});t.Timetable.Add(new TimetableEntry{StationId=other.Id,Kind=StopKind.Destination,Arrival="08:30"});project.Trains.Add(t);selectedTrain=t.Id;status=$"ADDED {t.Number} - D DUPLICATES";}
    void Duplicate(){var t=project.Trains.FirstOrDefault(x=>x.Id==selectedTrain);if(t==null)return;var c=JsonSerializer.Deserialize<TrainRun>(JsonSerializer.Serialize(t,ProjectJson.Options),ProjectJson.Options)!;c.Id=Guid.NewGuid();c.Number=t.Number+"-COPY";project.Trains.Add(c);selectedTrain=c.Id;status="TRAIN DUPLICATED";}
    void Delete(){if(selectedStation is Guid s){project.Stations.RemoveAll(x=>x.Id==s);selectedStation=null;status="STATION DELETED";}else if(selectedTrain is Guid t){project.Trains.RemoveAll(x=>x.Id==t);selectedTrain=null;status="TRAIN DELETED";}}
    void Save(){File.WriteAllText("project.railplanner",JsonSerializer.Serialize(project,ProjectJson.Options));status="SAVED project.railplanner";}void LoadProject(){if(!File.Exists("project.railplanner")){status="NO PROJECT FILE";return;}project=JsonSerializer.Deserialize<RailProject>(File.ReadAllText("project.railplanner"),ProjectJson.Options)??new();status="LOADED project.railplanner";}
    Vector2 ScreenToMap(Vector2 p)=>(p-new Vector2(280,54)-camera)/zoom;Vector2 MapToScreen(Vector2 p)=>p*zoom+new Vector2(280,54)+camera;
    protected override void Draw(GameTime t){GraphicsDevice.Clear(new Color(9,12,16));batch.Begin(samplerState:SamplerState.PointClamp);Rect(new(0,0,1440,54),new(18,22,28));Text("RAILPLANNER",new(18,15),Color.White,1);Text("F1 SELECT  F2 STATION  F3 SECTION  F4 TRAIN  F5 SAVE  F6 LOAD  F7 ANALYZE  F8 LINES  F9 RENAME  F10/F11 TRACKS",new(250,18),Color.LightGray,.55f);DrawMap();Sidebar();batch.End();base.Draw(t);}
    void DrawMap(){Rect(new(0,54,1440,846),new(11,15,20));for(int x=-1000;x<2000;x+=50){var p=MapToScreen(new(x,0));Rect(new((int)p.X,54,1,846),new(25,31,38));}for(int y=-1000;y<2000;y+=50){var p=MapToScreen(new(0,y));Rect(new(280,(int)p.Y,1160,1),new(25,31,38));}foreach(var l in project.Lines)foreach(var s in l.Sections){var q=s.Geometry.Select(x=>MapToScreen(new(x.X,x.Y))).ToList();var selected=selectedSection==s.Id;for(int i=0;i<q.Count-1;i++)Line(q[i],q[i+1],selected?Color.White:new Color(115,125,135),selected?4:2);if(q.Count>1)Text($"{l.Number}|{s.Number}",(q[0]+q[^1])/2-new Vector2(0,16),selected?Color.White:new Color(130,145,155),selected ? .7f : .55f);}foreach(var s in project.Stations){var p=MapToScreen(new(s.X,s.Y));bool sel=selectedStation==s.Id;Rect(new((int)p.X-4,(int)p.Y-4,sel?12:8,sel?12:8),sel?Color.White:new Color(220,220,220));Text(s.Code,p+new Vector2(8,-8),Color.LightGray,.65f);}}
    void Sidebar(){Rect(new(0,54,280,846),new(16,20,25));Text("LINES",new(18,74),Color.White,.82f);var y=104;foreach(var line in project.Lines){var active=selectedLine==line.Id;Text($"{line.Number}  {line.Name}",new(18,y),active?Color.White:Color.LightGray,.7f);y+=26;if(active){var route=LineRoute(line);if(route.Count>0){Text(string.Join(" - ",route.Select(x=>x.Code)),new(28,y),new Color(130,145,155),.52f);y+=30;}foreach(var sec in line.Sections){var secActive=selectedSection==sec.Id;var from=project.Stations.FirstOrDefault(x=>x.Id==sec.FromStationId)?.Code??"?";var to=project.Stations.FirstOrDefault(x=>x.Id==sec.ToStationId)?.Code??"?";Text($"{line.Number}|{sec.Number}",new(28,y),secActive?Color.White:new Color(150,165,175),.62f);Text($"{from} - {to}",new(105,y),secActive?Color.White:new Color(115,130,140),.55f);y+=36;}}y+=8;}Text("NETWORK",new(18,Math.Max(y+8,610)),Color.White,.72f);var ny=Math.Max(y+38,640);Text($"STATIONS {project.Stations.Count}",new(18,ny),Color.LightGray,.65f);Text($"LINES    {project.Lines.Count}",new(18,ny+22),Color.LightGray,.65f);Text($"TRAINS   {project.Trains.Count}",new(18,ny+44),Color.LightGray,.65f);Text("MODE "+mode,new(18,ny+78),Color.White,.65f);Text(status,new(18,ny+104),status.Contains("CONFLICT")?Color.OrangeRed:new Color(150,190,205),.55f);Text("ANALYSIS",new(18,ny+148),Color.White,.72f);Text($"CONFLICTS {analysis.Conflicts.Count}",new(18,ny+178),analysis.Conflicts.Count>0?Color.OrangeRed:Color.LightGray,.65f);Text($"WARNINGS  {analysis.Warnings.Count}",new(18,ny+200),analysis.Warnings.Count>0?Color.Gold:Color.LightGray,.65f);if(selectedStation is Guid id){var s=project.Stations.FirstOrDefault(x=>x.Id==id);if(s!=null){Text(s.Name,new(18,ny+240),Color.White,.72f);Text($"CODE {s.Code}",new(18,ny+268),Color.LightGray,.6f);Text($"TRACKS {s.Tracks}",new(18,ny+290),Color.LightGray,.6f);Text($"TYPE {s.Type}",new(18,ny+312),Color.LightGray,.6f);if(renamingStation){Text("EDIT NAME:",new(18,ny+340),Color.White,.58f);Text(stationNameBuffer.ToString()+"_",new(18,ny+362),Color.White,.62f);}}}if(selectedTrain is Guid tid){var tr=project.Trains.FirstOrDefault(x=>x.Id==tid);if(tr!=null){Text(tr.Number,new(18,ny+240),Color.White,.72f);Text(tr.Name,new(18,ny+268),Color.LightGray,.6f);Text("D = DUPLICATE",new(18,ny+296),Color.LightGray,.6f);}}Text("F9 RENAME STATION",new(18,830),Color.Gray,.55f);Text("F10 + TRACK   F11 - TRACK   DELETE REMOVE",new(18,850),Color.Gray,.5f);Text("ESC CANCEL",new(18,870),Color.Gray,.55f);}
    List<Station> LineRoute(RailwayLine line){var result=new List<Station>();foreach(var sec in line.Sections){var a=project.Stations.FirstOrDefault(x=>x.Id==sec.FromStationId);var b=project.Stations.FirstOrDefault(x=>x.Id==sec.ToStationId);if(a==null||b==null)continue;if(result.Count==0)result.Add(a);else if(result[^1].Id!=a.Id)result.Add(a);if(result[^1].Id!=b.Id)result.Add(b);}return result;}
    void Text(string s,Vector2 p,Color c,float z)=>batch.DrawString(font,s,p,c,0,Vector2.Zero,z,SpriteEffects.None,0);void Rect(Rectangle r,Color c)=>batch.Draw(pixel,r,c);void Line(Vector2 a,Vector2 b,Color c,int w){var d=b-a;batch.Draw(pixel,a,null,c,MathF.Atan2(d.Y,d.X),Vector2.Zero,new Vector2(d.Length(),w),SpriteEffects.None,0);}
}
